#include "\z\MMFW\addons\core\cfgAttributes\External.hpp"
#include "CfgAttributes\GearComboLoadAttribute.hpp"
#include "CfgAttributes\SystemTypeAttribute.hpp"
#include "CfgAttributes\ACEGearClassAttribute.hpp"
#include "CfgAttributes\ACEGearClassAttributeUnit.hpp"
#include "CfgAttributes\ManualGearTypeAttribute.hpp"
#include "CfgAttributes\GearPresetAttribute.hpp"
