#include "\a3\3DEN\UI\macros.inc"
#include "\a3\3DEN\UI\resincl.inc"

class Display;
class DisplaySimulated;
class ctrlControlsGroupNoScrollbars;
class ctrlButton;
class ctrlButtonPictureKeepAspect;
class ctrlDefaultText;
class ctrlDefault;
class ctrlMenu;
class ctrlMenuStrip;
class ctrlToolbox;
class ctrlCheckbox;
class ctrlCombo;
class ctrlEdit;
class ctrlStatic;
class ctrlXSliderH;
class ctrlStaticFrame;
class ctrlStaticPicture;
class ctrlTree;
class ctrlListbox;
class ControlsBackground;
class ctrlStaticBackground;
class ctrlStaticFooter;
class ctrlStaticTitle;
class ctrlControlsGroup;
class ctrlButtonOK;
class ctrlButtonCancel;
class ctrlCheckboxBaseline;
class Type;
class Init;
class State;
class Transformation;
class Control;
class Presence;
class Size;
