class GVAR(Presets_BLUFOR) {
    displayName = "Blufor Gear Presets";
    collapsed = 1;
    class Attributes {
        class GVAR(ACE_Arsenal_GearPresets_BLUFOR) {
            property = QGVAR(ACE_Arsenal_GearPresets_BLUFOR);
            displayName = "Gear Presets";
            tooltip = "";
            control = QGVAR(PresetsCombo_BLUFOR);
            typeName = "STRING";
            expression = SCENARIO_EXPRESSION;
            defaultValue = "'None'";
        };
    };
};

class GVAR(ACE_Arsenal_Blufor) {
    displayName = "Blufor ACE Gear Settings";
    collapsed = 1;
    class Attributes {
        GEAR_TYPECONFIG_ACEAR(Blufor,SQL);
        GEAR_TYPECONFIG_ACEAR(Blufor,TL);
        GEAR_TYPECONFIG_ACEAR(Blufor,RFL);
        GEAR_TYPECONFIG_ACEAR(Blufor,RFLAT);
        GEAR_TYPECONFIG_ACEAR(Blufor,AR);
        GEAR_TYPECONFIG_ACEAR(Blufor,GRN);
        GEAR_TYPECONFIG_ACEAR(Blufor,VCRW);
        GEAR_TYPECONFIG_ACEAR(Blufor,VCMD);
        GEAR_TYPECONFIG_ACEAR(Blufor,OFF);
        GEAR_TYPECONFIG_ACEAR(Blufor,TWOIC);
        GEAR_TYPECONFIG_ACEAR(Blufor,MED);
        GEAR_TYPECONFIG_ACEAR(Blufor,AT);
        GEAR_TYPECONFIG_ACEAR(Blufor,AAT);
        GEAR_TYPECONFIG_ACEAR(Blufor,MG);
        GEAR_TYPECONFIG_ACEAR(Blufor,AMG);
        GEAR_TYPECONFIG_ACEAR(Blufor,MKS);
        GEAR_TYPECONFIG_ACEAR(Blufor,RTO);
        GEAR_TYPECONFIG_ACEAR(Blufor,FAC);
        GEAR_TYPECONFIG_ACEAR(Blufor,FO);
        GEAR_TYPECONFIG_ACEAR(Blufor,ENG);
        GEAR_TYPECONFIG_ACEAR(Blufor,EOD);
        GEAR_TYPECONFIG_ACEAR(Blufor,HAT);
        GEAR_TYPECONFIG_ACEAR(Blufor,AHAT);
        GEAR_TYPECONFIG_ACEAR(Blufor,MORTL);
        GEAR_TYPECONFIG_ACEAR(Blufor,MOR);
        GEAR_TYPECONFIG_ACEAR(Blufor,APLT);
        GEAR_TYPECONFIG_ACEAR(Blufor,ACRW);
        GEAR_TYPECONFIG_ACEAR(Blufor,CUS1);
        GEAR_TYPECONFIG_ACEAR(Blufor,CUS2);
        GEAR_TYPECONFIG_ACEAR(Blufor,CUS3);
        GEAR_TYPECONFIG_ACEAR(Blufor,CUS4);
        GEAR_TYPECONFIG_ACEAR(Blufor,CUS5);
    };
};
class GVAR(Olsen_Blufor) {
    displayName = "Blufor Olsen Gear Settings";
    collapsed = 1;
    class Attributes {
        GEAR_TYPECONFIG_OLSEN(Blufor,SQL);
        GEAR_TYPECONFIG_OLSEN(Blufor,TL);
        GEAR_TYPECONFIG_OLSEN(Blufor,RFL);
        GEAR_TYPECONFIG_OLSEN(Blufor,RFLAT);
        GEAR_TYPECONFIG_OLSEN(Blufor,AR);
        GEAR_TYPECONFIG_OLSEN(Blufor,GRN);
        GEAR_TYPECONFIG_OLSEN(Blufor,VCRW);
        GEAR_TYPECONFIG_OLSEN(Blufor,VCMD);
        GEAR_TYPECONFIG_OLSEN(Blufor,OFF);
        GEAR_TYPECONFIG_OLSEN(Blufor,TWOIC);
        GEAR_TYPECONFIG_OLSEN(Blufor,MED);
        GEAR_TYPECONFIG_OLSEN(Blufor,AT);
        GEAR_TYPECONFIG_OLSEN(Blufor,AAT);
        GEAR_TYPECONFIG_OLSEN(Blufor,MG);
        GEAR_TYPECONFIG_OLSEN(Blufor,AMG);
        GEAR_TYPECONFIG_OLSEN(Blufor,MKS);
        GEAR_TYPECONFIG_OLSEN(Blufor,RTO);
        GEAR_TYPECONFIG_OLSEN(Blufor,FAC);
        GEAR_TYPECONFIG_OLSEN(Blufor,FO);
        GEAR_TYPECONFIG_OLSEN(Blufor,ENG);
        GEAR_TYPECONFIG_OLSEN(Blufor,EOD);
        GEAR_TYPECONFIG_OLSEN(Blufor,HAT);
        GEAR_TYPECONFIG_OLSEN(Blufor,AHAT);
        GEAR_TYPECONFIG_OLSEN(Blufor,MORTL);
        GEAR_TYPECONFIG_OLSEN(Blufor,MOR);
        GEAR_TYPECONFIG_OLSEN(Blufor,APLT);
        GEAR_TYPECONFIG_OLSEN(Blufor,ACRW);
        GEAR_TYPECONFIG_OLSEN(Blufor,CUS1);
        GEAR_TYPECONFIG_OLSEN(Blufor,CUS2);
        GEAR_TYPECONFIG_OLSEN(Blufor,CUS3);
        GEAR_TYPECONFIG_OLSEN(Blufor,CUS4);
        GEAR_TYPECONFIG_OLSEN(Blufor,CUS5);
    };
};
