class GVAR(Presets_Indfor) {
    displayName = "Indfor Gear Presets";
    collapsed = 0;
    class Attributes {
        class GVAR(ACE_Arsenal_GearPresets_Indfor) {
            property = QGVAR(ACE_Arsenal_GearPresets_Indfor);
            displayName = "Gear Presets";
            tooltip = "";
            control = QGVAR(PresetsCombo_Indfor);
            typeName = "STRING";
            expression = SCENARIO_EXPRESSION;
            defaultValue = "'None'";
        };
    };
};

class GVAR(ACE_Arsenal_Indfor) {
    displayName = "Indfor ACE Gear Settings";
    collapsed = 1;
    class Attributes {
        GEAR_TYPECONFIG_ACEAR(Indfor,SQL);
        GEAR_TYPECONFIG_ACEAR(Indfor,TL);
        GEAR_TYPECONFIG_ACEAR(Indfor,RFL);
        GEAR_TYPECONFIG_ACEAR(Indfor,RFLAT);
        GEAR_TYPECONFIG_ACEAR(Indfor,AR);
        GEAR_TYPECONFIG_ACEAR(Indfor,GRN);
        GEAR_TYPECONFIG_ACEAR(Indfor,VCRW);
        GEAR_TYPECONFIG_ACEAR(Indfor,VCMD);
        GEAR_TYPECONFIG_ACEAR(Indfor,OFF);
        GEAR_TYPECONFIG_ACEAR(Indfor,TWOIC);
        GEAR_TYPECONFIG_ACEAR(Indfor,MED);
        GEAR_TYPECONFIG_ACEAR(Indfor,AT);
        GEAR_TYPECONFIG_ACEAR(Indfor,AAT);
        GEAR_TYPECONFIG_ACEAR(Indfor,MG);
        GEAR_TYPECONFIG_ACEAR(Indfor,AMG);
        GEAR_TYPECONFIG_ACEAR(Indfor,MKS);
        GEAR_TYPECONFIG_ACEAR(Indfor,RTO);
        GEAR_TYPECONFIG_ACEAR(Indfor,FAC);
        GEAR_TYPECONFIG_ACEAR(Indfor,FO);
        GEAR_TYPECONFIG_ACEAR(Indfor,ENG);
        GEAR_TYPECONFIG_ACEAR(Indfor,EOD);
        GEAR_TYPECONFIG_ACEAR(Indfor,HAT);
        GEAR_TYPECONFIG_ACEAR(Indfor,AHAT);
        GEAR_TYPECONFIG_ACEAR(Indfor,MORTL);
        GEAR_TYPECONFIG_ACEAR(Indfor,MOR);
        GEAR_TYPECONFIG_ACEAR(Indfor,APLT);
        GEAR_TYPECONFIG_ACEAR(Indfor,ACRW);
        GEAR_TYPECONFIG_ACEAR(Indfor,CUS1);
        GEAR_TYPECONFIG_ACEAR(Indfor,CUS2);
        GEAR_TYPECONFIG_ACEAR(Indfor,CUS3);
        GEAR_TYPECONFIG_ACEAR(Indfor,CUS4);
        GEAR_TYPECONFIG_ACEAR(Indfor,CUS5);
    };
};
class GVAR(Olsen_Indfor) {
    displayName = "Indfor Olsen Gear Settings";
    collapsed = 1;
    class Attributes {
        GEAR_TYPECONFIG_OLSEN(Indfor,SQL);
        GEAR_TYPECONFIG_OLSEN(Indfor,TL);
        GEAR_TYPECONFIG_OLSEN(Indfor,RFL);
        GEAR_TYPECONFIG_OLSEN(Indfor,RFLAT);
        GEAR_TYPECONFIG_OLSEN(Indfor,AR);
        GEAR_TYPECONFIG_OLSEN(Indfor,GRN);
        GEAR_TYPECONFIG_OLSEN(Indfor,VCRW);
        GEAR_TYPECONFIG_OLSEN(Indfor,VCMD);
        GEAR_TYPECONFIG_OLSEN(Indfor,OFF);
        GEAR_TYPECONFIG_OLSEN(Indfor,TWOIC);
        GEAR_TYPECONFIG_OLSEN(Indfor,MED);
        GEAR_TYPECONFIG_OLSEN(Indfor,AT);
        GEAR_TYPECONFIG_OLSEN(Indfor,AAT);
        GEAR_TYPECONFIG_OLSEN(Indfor,MG);
        GEAR_TYPECONFIG_OLSEN(Indfor,AMG);
        GEAR_TYPECONFIG_OLSEN(Indfor,MKS);
        GEAR_TYPECONFIG_OLSEN(Indfor,RTO);
        GEAR_TYPECONFIG_OLSEN(Indfor,FAC);
        GEAR_TYPECONFIG_OLSEN(Indfor,FO);
        GEAR_TYPECONFIG_OLSEN(Indfor,ENG);
        GEAR_TYPECONFIG_OLSEN(Indfor,EOD);
        GEAR_TYPECONFIG_OLSEN(Indfor,HAT);
        GEAR_TYPECONFIG_OLSEN(Indfor,AHAT);
        GEAR_TYPECONFIG_OLSEN(Indfor,MORTL);
        GEAR_TYPECONFIG_OLSEN(Indfor,MOR);
        GEAR_TYPECONFIG_OLSEN(Indfor,APLT);
        GEAR_TYPECONFIG_OLSEN(Indfor,ACRW);
        GEAR_TYPECONFIG_OLSEN(Indfor,CUS1);
        GEAR_TYPECONFIG_OLSEN(Indfor,CUS2);
        GEAR_TYPECONFIG_OLSEN(Indfor,CUS3);
        GEAR_TYPECONFIG_OLSEN(Indfor,CUS4);
        GEAR_TYPECONFIG_OLSEN(Indfor,CUS5);
    };
};
